//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public decimal ID_CAPACITACIO { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public string RUT { get; set; }
        public System.DateTime FECHA_HORA_REGISTRO { get; set; }
        public System.DateTime FECHA_HORA_REALIZACION { get; set; }
        public string RUT_PROFESIONAL2 { get; set; }
        public string RUT_PROFESIONAL3 { get; set; }
        public decimal REALIZADO { get; set; }
        public decimal DAR_BAJA { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
