//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_EMPRESA
    {
        public CLIENTE_EMPRESA()
        {
            this.CHEQUEO = new HashSet<CHEQUEO>();
            this.FACTURA = new HashSet<FACTURA>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public string RUT { get; set; }
        public decimal ID_GIRO { get; set; }
        public decimal ID_COMUNA { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public string CORREO { get; set; }
        public decimal CLIENTE_MOROSO { get; set; }
    
        public virtual ICollection<CHEQUEO> CHEQUEO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual GIRO GIRO { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
