//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRO
    {
        public GIRO()
        {
            this.CLIENTE_EMPRESA = new HashSet<CLIENTE_EMPRESA>();
        }
    
        public decimal ID_GIRO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<CLIENTE_EMPRESA> CLIENTE_EMPRESA { get; set; }
    }
}
