//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLAMADO
    {
        public decimal ID_LLAMADO { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public string RUT { get; set; }
        public string RUT_EMPRESA { get; set; }
        public System.DateTime FECHA_HORA_LLAMADO { get; set; }
        public decimal DURACION_MIN { get; set; }
        public string RUTA_GRABACION { get; set; }
        public string OBSERVACION { get; set; }
        public decimal LLAMADA_EXTRA { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
