//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIVO_ASESORIA
    {
        public MOTIVO_ASESORIA()
        {
            this.ASESORIA = new HashSet<ASESORIA>();
        }
    
        public decimal ID_MOTIVO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<ASESORIA> ASESORIA { get; set; }
    }
}
