//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTA
    {
        public decimal ID_MULTA { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public string RUT { get; set; }
        public System.DateTime FECHA_HORA_MULTA { get; set; }
        public System.DateTime FECHA_HORA_REGISTRO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal VALOR_MULTA { get; set; }
        public decimal RUTA_DOC_MULTA { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
