//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public PAGO()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public decimal ID_PAGO { get; set; }
        public decimal FUERA_DE_PLAZO { get; set; }
        public System.DateTime FECHA_HORA_PAGO { get; set; }
    
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
