//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.ACCIDENTE = new HashSet<ACCIDENTE>();
            this.ASESORIA = new HashSet<ASESORIA>();
            this.CAPACITACION = new HashSet<CAPACITACION>();
            this.FACTURA = new HashSet<FACTURA>();
            this.LLAMADO = new HashSet<LLAMADO>();
            this.MULTA = new HashSet<MULTA>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
            this.VISITA = new HashSet<VISITA>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string RUT_EMPRESA { get; set; }
        public decimal ID_PLAN { get; set; }
        public System.DateTime FECHA_VINCULACION { get; set; }
        public decimal DIA_FACTURACION { get; set; }
        public decimal DIA_CORTE { get; set; }
        public decimal MODCHECK_AÑO { get; set; }
        public decimal VISITAS_MES { get; set; }
        public decimal CAPACITACION_MES { get; set; }
        public decimal ASESORIAS_MES { get; set; }
        public decimal ACTINFO_MES { get; set; }
        public decimal DAR_BAJA { get; set; }
    
        public virtual ICollection<ACCIDENTE> ACCIDENTE { get; set; }
        public virtual ICollection<ASESORIA> ASESORIA { get; set; }
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
        public virtual CLIENTE_EMPRESA CLIENTE_EMPRESA { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual ICollection<LLAMADO> LLAMADO { get; set; }
        public virtual ICollection<MULTA> MULTA { get; set; }
        public virtual PLAN_PAGO PLAN_PAGO { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual ICollection<VISITA> VISITA { get; set; }
    }
}
