//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ACCIDENTE = new HashSet<ACCIDENTE>();
            this.ASESORIA = new HashSet<ASESORIA>();
            this.CAPACITACION = new HashSet<CAPACITACION>();
            this.LLAMADO = new HashSet<LLAMADO>();
            this.MULTA = new HashSet<MULTA>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
            this.VISITA = new HashSet<VISITA>();
        }
    
        public string RUT { get; set; }
        public long ID_TIPO { get; set; }
        public string PASS { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOP { get; set; }
        public string APELLIDOM { get; set; }
        public string CORREO { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public long MOROSO { get; set; }
        public long DAR_BAJA { get; set; }
        public string RUT_EMPRESA { get; set; }
    
        public virtual ICollection<ACCIDENTE> ACCIDENTE { get; set; }
        public virtual ICollection<ASESORIA> ASESORIA { get; set; }
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
        public virtual ICollection<LLAMADO> LLAMADO { get; set; }
        public virtual ICollection<MULTA> MULTA { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<VISITA> VISITA { get; set; }
    }
}
