//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgosWPF.PrevencionWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrevencionWCF.IPrevencion")]
    public interface IPrevencion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ValidarUsuario", ReplyAction="http://tempuri.org/IPrevencion/ValidarUsuarioResponse")]
        bool ValidarUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ValidarUsuario", ReplyAction="http://tempuri.org/IPrevencion/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadUsuario", ReplyAction="http://tempuri.org/IPrevencion/ReadUsuarioResponse")]
        string ReadUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadUsuario", ReplyAction="http://tempuri.org/IPrevencion/ReadUsuarioResponse")]
        System.Threading.Tasks.Task<string> ReadUsuarioAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrevencionChannel : PrevencionRiesgosWPF.PrevencionWCF.IPrevencion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrevencionClient : System.ServiceModel.ClientBase<PrevencionRiesgosWPF.PrevencionWCF.IPrevencion>, PrevencionRiesgosWPF.PrevencionWCF.IPrevencion {
        
        public PrevencionClient() {
        }
        
        public PrevencionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrevencionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrevencionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrevencionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string xml) {
            return base.Channel.ValidarUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string xml) {
            return base.Channel.ValidarUsuarioAsync(xml);
        }
        
        public string ReadUsuario(string xml) {
            return base.Channel.ReadUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<string> ReadUsuarioAsync(string xml) {
            return base.Channel.ReadUsuarioAsync(xml);
        }
    }
}
