//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCIDENTE
    {
        public decimal ID_ACCIDENTE { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public string RUT { get; set; }
        public string RUT_ACCIDENTADO { get; set; }
        public string NOMBRE_ACCIDENTADO { get; set; }
        public string APELLIDOP_ACCIDENTADO { get; set; }
        public string APELLIDOM_ACCIDENTADO { get; set; }
        public System.DateTime FECHA_HORA_ACCIDENTE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
