//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public decimal NRO_FACTURA { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public string RUT_EMPRESA { get; set; }
        public string GIRO_EMPRESA { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string DIRECCION_EMPRESA { get; set; }
        public string TELEFONO_EMPRESA { get; set; }
        public string RUT_EMPRESA_CLI { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string GIRO_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string COMUNA_CLIENTE { get; set; }
        public string CIUDAD_CLIENTE { get; set; }
        public string CONTACTO_CLIENTE { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal VALOR_NETO { get; set; }
        public decimal IVA { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ID_PAGO { get; set; }
    
        public virtual CLIENTE_EMPRESA CLIENTE_EMPRESA { get; set; }
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual PAGO PAGO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
