//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_PAGO
    {
        public PLAN_PAGO()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal ID_PLAN { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal COSTO_FIJO { get; set; }
        public decimal CANT_VISITAS_MES { get; set; }
        public decimal MAX_MODCHECK_ANIO { get; set; }
        public decimal COST_EXT_MODCHECK { get; set; }
        public decimal MAX_CAPAC_MES { get; set; }
        public decimal COST_EXT_CAPAC { get; set; }
        public decimal HORA_INI_LLAMADAS { get; set; }
        public decimal HORA_FIN_LLAMADAS { get; set; }
        public decimal COST_EXT_LLAMADAS { get; set; }
        public decimal MAX_ASESORIAS_MES { get; set; }
        public decimal COST_EXT_ASESO { get; set; }
        public decimal MAX_ACTINFO_MES { get; set; }
        public decimal COST_EXT_ACTINFO { get; set; }
        public decimal DAR_BAJA { get; set; }
    
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
