//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrevencionRiesgosEntities : DbContext
    {
        public PrevencionRiesgosEntities()
            : base("name=PrevencionRiesgosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCIDENTE> ACCIDENTE { get; set; }
        public DbSet<ASESORIA> ASESORIA { get; set; }
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CHEQUEO> CHEQUEO { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<CLIENTE_EMPRESA> CLIENTE_EMPRESA { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<GIRO> GIRO { get; set; }
        public DbSet<LLAMADO> LLAMADO { get; set; }
        public DbSet<MOTIVO_ASESORIA> MOTIVO_ASESORIA { get; set; }
        public DbSet<MULTA> MULTA { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PLAN_PAGO> PLAN_PAGO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<SOLICITUD> SOLICITUD { get; set; }
        public DbSet<TIPO_SOLICITUD> TIPO_SOLICITUD { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VISITA> VISITA { get; set; }
    }
}
