//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public decimal ID_SOLICITUD { get; set; }
        public decimal ID_SERVICIO { get; set; }
        public decimal ID_TIPO_SOLICITUD { get; set; }
        public string RUT { get; set; }
        public string MENSAJE { get; set; }
        public decimal CERRADA { get; set; }
        public decimal DAR_BAJA { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual TIPO_SOLICITUD TIPO_SOLICITUD { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
