//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgos.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public VISITA()
        {
            this.CHEQUEO = new HashSet<CHEQUEO>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public decimal ID_VISITA { get; set; }
        public string RUT { get; set; }
        public string OBSERVACION { get; set; }
        public string PROPUESTA_MEJORA { get; set; }
        public decimal REALIZADO { get; set; }
        public decimal DAR_BAJA { get; set; }
    
        public virtual ICollection<CHEQUEO> CHEQUEO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
