//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrevencionRiesgosWPF.PrevencionRiesgosWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrevencionRiesgosWCF.IPrevencion")]
    public interface IPrevencion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ValidarUsuario", ReplyAction="http://tempuri.org/IPrevencion/ValidarUsuarioResponse")]
        bool ValidarUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ValidarUsuario", ReplyAction="http://tempuri.org/IPrevencion/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadUsuario", ReplyAction="http://tempuri.org/IPrevencion/ReadUsuarioResponse")]
        string ReadUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadUsuario", ReplyAction="http://tempuri.org/IPrevencion/ReadUsuarioResponse")]
        System.Threading.Tasks.Task<string> ReadUsuarioAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ValidarUsuarioJava", ReplyAction="http://tempuri.org/IPrevencion/ValidarUsuarioJavaResponse")]
        int ValidarUsuarioJava(string r, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ValidarUsuarioJava", ReplyAction="http://tempuri.org/IPrevencion/ValidarUsuarioJavaResponse")]
        System.Threading.Tasks.Task<int> ValidarUsuarioJavaAsync(string r, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadTipoUsuario", ReplyAction="http://tempuri.org/IPrevencion/ReadTipoUsuarioResponse")]
        string ReadTipoUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadTipoUsuario", ReplyAction="http://tempuri.org/IPrevencion/ReadTipoUsuarioResponse")]
        System.Threading.Tasks.Task<string> ReadTipoUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadUsuariosCollection", ReplyAction="http://tempuri.org/IPrevencion/ReadUsuariosCollectionResponse")]
        string ReadUsuariosCollection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/ReadUsuariosCollection", ReplyAction="http://tempuri.org/IPrevencion/ReadUsuariosCollectionResponse")]
        System.Threading.Tasks.Task<string> ReadUsuariosCollectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/CrearUsuario", ReplyAction="http://tempuri.org/IPrevencion/CrearUsuarioResponse")]
        bool CrearUsuario(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrevencion/CrearUsuario", ReplyAction="http://tempuri.org/IPrevencion/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrevencionChannel : PrevencionRiesgosWPF.PrevencionRiesgosWCF.IPrevencion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrevencionClient : System.ServiceModel.ClientBase<PrevencionRiesgosWPF.PrevencionRiesgosWCF.IPrevencion>, PrevencionRiesgosWPF.PrevencionRiesgosWCF.IPrevencion {
        
        public PrevencionClient() {
        }
        
        public PrevencionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrevencionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrevencionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrevencionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string xml) {
            return base.Channel.ValidarUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string xml) {
            return base.Channel.ValidarUsuarioAsync(xml);
        }
        
        public string ReadUsuario(string xml) {
            return base.Channel.ReadUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<string> ReadUsuarioAsync(string xml) {
            return base.Channel.ReadUsuarioAsync(xml);
        }
        
        public int ValidarUsuarioJava(string r, string p) {
            return base.Channel.ValidarUsuarioJava(r, p);
        }
        
        public System.Threading.Tasks.Task<int> ValidarUsuarioJavaAsync(string r, string p) {
            return base.Channel.ValidarUsuarioJavaAsync(r, p);
        }
        
        public string ReadTipoUsuario() {
            return base.Channel.ReadTipoUsuario();
        }
        
        public System.Threading.Tasks.Task<string> ReadTipoUsuarioAsync() {
            return base.Channel.ReadTipoUsuarioAsync();
        }
        
        public string ReadUsuariosCollection() {
            return base.Channel.ReadUsuariosCollection();
        }
        
        public System.Threading.Tasks.Task<string> ReadUsuariosCollectionAsync() {
            return base.Channel.ReadUsuariosCollectionAsync();
        }
        
        public bool CrearUsuario(string xml) {
            return base.Channel.CrearUsuario(xml);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xml) {
            return base.Channel.CrearUsuarioAsync(xml);
        }
    }
}
